version: 2

models:
  # Staging Models
  - name: staging_purchase_logs
    config:
      contract:
        enforced: true
    columns:
      - name: time_order_received_utc
        data_type: TIMESTAMP
      - name: purchase_key
        data_type: VARCHAR
      - name: customer_key
        data_type: VARCHAR
      - name: delivery_distance_line_meters
        data_type: INTEGER
      - name: wolt_service_fee
        data_type: DECIMAL(10,2)
      - name: courier_base_fee
        data_type: DECIMAL(10,2)
      - name: total_basket_value
        data_type: DECIMAL(10,2)
      - name: basket_items
        data_type: VARCHAR
      - name: loaded_timestamp
        data_type: TIMESTAMP WITH TIME ZONE

      
  - name: staging_promos
    config:
      contract:
        enforced: true
    columns:
      - name: promo_start_date
        data_type: DATE
      - name: promo_end_date
        data_type: DATE
      - name: item_key
        data_type: VARCHAR
      - name: promo_type
        data_type: VARCHAR
      - name: discount_in_percentage
        data_type: INTEGER
      - name: loaded_timestamp
        data_type: TIMESTAMP WITH TIME ZONE

  - name: staging_item_logs
    config:
      contract:
        enforced: true
    columns:
      - name: log_item_id
        data_type: VARCHAR
      - name: item_key
        data_type: VARCHAR
      - name: brand_name
        data_type: VARCHAR
      - name: item_category
        data_type: VARCHAR
      - name: name_array
        data_type: VARCHAR
      - name: number_of_units
        data_type: INTEGER
      - name: weight_in_grams
        data_type: INTEGER
      - name: currency
        data_type: VARCHAR
      - name: product_base_price
        data_type: DECIMAL(10,4)
      - name: product_base_price_ex_vat
        data_type: DOUBLE
      - name: vat_rate
        data_type: DECIMAL(10,2)
      - name: record_valid_from
        data_type: TIMESTAMP
      - name: record_valid_to
        data_type: TIMESTAMP

  # Dimension Tables
  - name: dim_customer
    config:
      contract:
        enforced: true
    columns:
      - name: customer_id
        data_type: VARCHAR
        constraints:
          - type: primary_key
      - name: first_order_date
        data_type: DATE
      - name: total_orders
        data_type: BIGINT
      - name: is_repeat_customer
        data_type: BOOLEAN
      - name: total_spent
        data_type: DECIMAL(38,2)

  - name: dim_items_scd
    config:
      contract:
        enforced: true
    columns:
      - name: log_item_id
        data_type: VARCHAR
      - name: item_key
        data_type: VARCHAR
      - name: brand_name
        data_type: VARCHAR
      - name: item_category
        data_type: VARCHAR
      - name: product_name
        data_type: VARCHAR
        description: "Product name, prioritizing English if available"
      - name: number_of_units
        data_type: INTEGER
      - name: weight_in_grams
        data_type: INTEGER
      - name: currency
        data_type: VARCHAR
      - name: product_base_price
        data_type: DECIMAL(10,4)
      - name: product_base_price_ex_vat
        data_type: DOUBLE
      - name: vat_rate
        data_type: DECIMAL(10,2)
      - name: record_valid_from
        data_type: TIMESTAMP
      - name: record_valid_to
        data_type: TIMESTAMP

  - name: dim_items
    config:
      contract:
        enforced: true
    columns:
      - name: item_key
        data_type: VARCHAR
      - name: brand_name
        data_type: VARCHAR
      - name: item_category
        data_type: VARCHAR
      - name: product_name
        data_type: VARCHAR
        description: "Product name, prioritizing English if available"
      - name: number_of_units
        data_type: INTEGER
      - name: weight_in_grams
        data_type: INTEGER
      - name: currency
        data_type: VARCHAR
      - name: product_base_price
        data_type: DECIMAL(10,4)
      - name: product_base_price_ex_vat
        data_type: DOUBLE
      - name: vat_rate
        data_type: DECIMAL(10,2)
      - name: record_valid_from
        data_type: TIMESTAMP

  - name: dim_time
    config:
      contract:
        enforced: true
    columns:
      - name: calendar_date
        data_type: DATE
        constraints:
          - type: primary_key
      - name: year
        data_type: BIGINT
      - name: month
        data_type: BIGINT
      - name: day
        data_type: BIGINT
      - name: day_of_week
        data_type: BIGINT

  - name: dim_promotions
    config:
      contract:
        enforced: true
    columns:
      - name: promo_id
        data_type: VARCHAR
        constraints:
          - type: primary_key
      - name: promo_start_date
        data_type: DATE
      - name: promo_end_date
        data_type: DATE
      - name: item_key
        data_type: VARCHAR
      - name: promo_type
        data_type: VARCHAR
      - name: discount_in_percentage
        data_type: INTEGER
      - name: loaded_timestamp
        data_type: TIMESTAMP WITH TIME ZONE

  - name: fact_order
    config:
      contract:
        enforced: true
    columns:
      - name: order_id
        data_type: VARCHAR
        constraints:
          - type: primary_key 
      - name: customer_id
        data_type: VARCHAR
      - name: order_date
        data_type: DATE
      - name: order_timestamp
        data_type: TIMESTAMP
      - name: delivery_distance_line_meters
        data_type: INTEGER
      - name: wolt_service_fee
        data_type: DECIMAL(10,2)
      - name: courier_base_fee
        data_type: DECIMAL(10,2)
      - name: total_basket_value
        data_type: DECIMAL(10,2)
      - name: loaded_timestamp
        data_type: TIMESTAMP WITH TIME ZONE

  - name: fact_order_item
    config:
      contract:
        enforced: true
    columns:
      - name: customer_id
        data_type: VARCHAR  
      - name: order_id
        data_type: VARCHAR
      - name: order_item_id
        data_type: VARCHAR
      - name: item_id
        data_type: VARCHAR
      - name: order_date
        data_type: DATE
      - name: order_timestamp
        data_type: TIMESTAMP    
      - name: product_name
        data_type: VARCHAR  
      - name: brand_name
        data_type: VARCHAR
      - name: item_category
        data_type: VARCHAR
      - name: currency
        data_type: VARCHAR  
      - name: product_price
        data_type: DECIMAL(10,4) 
      - name: product_price_ex_vat
        data_type: DOUBLE  
      - name: weight_in_grams
        data_type: INTEGER
      - name: had_promotion
        data_type: BOOLEAN
      - name: discount
        data_type: INTEGER
      - name: loaded_timestamp
        data_type: TIMESTAMP WITH TIME ZONE

