# https://docs.getdbt.com/docs/core/connect-data-platform/profiles.yml

wolt_data_model:
  target: local
  outputs:
    local:
      type: duckdb
      path: "{{ env_var('DUCKDB_FILE_PATH') }}"
      schema: wolt_data_model