## Refer to Using dbt with Dagster, part one for info about this file:
## https://docs.dagster.io/integrations/dbt/using-dbt-with-dagster/part-one#step-2-create-a-duckdb-profile

wolt_data_store:
  target: local
  outputs:
    local:
      type: duckdb
      path: "{{ env_var('DUCKDB_FILE_PATH') }}"
      schema: wolt_data_model